/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hono
 * API for greeting users
 * OpenAPI spec version: 1.0.0
 */

export interface Product {
  id: string;
  boxCount: number;
  shippingMethod: string;
  productTemperature: string;
  configurationCount: number;
  productCode: string;
  productName: string;
}
