/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hono
 * API for greeting users
 * OpenAPI spec version: 1.0.0
 */
import type { Product } from './product';

export interface ProductsResponse {
  data: Product[];
}
