/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hono
 * API for greeting users
 * OpenAPI spec version: 1.0.0
 */
import type { ProductsResponse } from "../model";

/**
 * @summary 모든 제품 목록 조회
 */
export type getApiProductsResponse = {
  data: ProductsResponse;
  status: number;
  headers: Headers;
};

export const getGetApiProductsUrl = () => {
  return `http://localhost:8787/api/products`;
};

export const getApiProducts = async (
  options?: RequestInit
): Promise<getApiProductsResponse> => {
  const res = await fetch(getGetApiProductsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getApiProductsResponse["data"] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApiProductsResponse;
};
